# config.toml
# Selects which implementation module to use for each pluggable stage
# of the auto_index_selector pipeline. `main.py` reads this file and
# dynamically imports the chosen module for each stage.

[candidate_generation]
# Possible values: cg_auto_admin, cg_dta, cg_rule_based, cg_extend
module = "cg_rule_based"
 
[config_selection]
# Possible values: cs_greedy, cs_drop, cs_extend
module = "cs_greedy"
 
[config_selection.cs_greedy]
# m -> (seed), k-> (limit on number of candidate indexes)
m = 2
k = 2
 
[config_selection.cs_drop]
# s -> storage budget
s = 400
 
[workload]
# Possible values: tpchWorkload, tpcdsWorkload, tpccWorkload
module = "tpcdsWorkload"